version: '3'
services:
  nginx:
    image: loadbalancer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/reto3.eafit.xyz/fullchain.pem:/etc/letsencrypt/live/reto3.eafit.xyz/fullchain.pem
      - /etc/letsencrypt/live/reto3.eafit.xyz/privkey.pem:/etc/letsencrypt/live/reto3.eafit.xyz/privkey.pem
    restart: always
